
#ifndef __APP_VERSION_H__
#define __APP_VERSION_H__

 
#define DCMAPP_NAME				"PXSDcmViewer"
 
#define DCMAPP_VERSION_MAJOR		1
#define DCMAPP_VERSION_MINOR		0
#define DCMAPP_VERSION_SUB			0
#define DCMAPP_VERSION_MICRO		0	
 

#ifdef _DEBUG
#define DCMAPP_VERSION_NAME		Debug
#else
#define DCMAPP_VERSION_NAME		
#endif

#define DCMAPP_VERSION_FULL		DCMAPP_VERSION_DOT DCMAPP_VERSION_NAME
#define DCMAPP_VERSION_STRING		DCMAPP_QSTRING(DCMAPP_VERSION_FULL)

#define DCMAPP_VERSION_DOT			DCMAPP_VERSION_MAJOR.DCMAPP_VERSION_MINOR.DCMAPP_VERSION_SUB.DCMAPP_VERSION_MICRO
#define DCMAPP_VERSION_COMMA		DCMAPP_VERSION_MAJOR,DCMAPP_VERSION_MINOR,DCMAPP_VERSION_SUB,DCMAPP_VERSION_MICRO

#define DCMAPP_QSTRING(s)			DCMAPP_QQSTRING(s)
#define DCMAPP_QQSTRING(s)			#s

#endif //__APP_VERSION_H__
