/***********************************************************************
 * $Id: ProgressAPI.h 35 2008-08-06 02:57:21Z atsushi $
 *---------------------------------------------------------------------
  
 *-------------------------------------------------------------------
 */

#ifndef PROGRESS_API_H
#define PROGRESS_API_H

#include <string>
#include <string.h>
#include <stdio.h> 
#include "AqCore/TRPlatform.h"
#include "rtvloadoption.h"
#include "CommandLine.h"
#include "JobControl.h"
#include "Job.h"
#include "PxNetDB.h"
#include "JobInfo.h"

/*
 *	Some abstract interfaces:
 *	
 *		JobInfoPublisher
 *		JobInfoSubscriber
 *
 */


//----------------------------------------------------------
//Progress API class
//
//All Progress API communcation is between the Process and the QueueManager
//
class ProgressAPI
{
public:

	int Initialize(int iTotal = 0, int iCompleted = 0, int iUserID = 1, std::string iJobType = "Anonymous");

	int GetTotalUnits(void);
	int GetCompletedUnits(void);
	int SetCompletedUnits(int iCompleted);

	//	Return values: one of eJobStatus if ok, otherwise, -1
	int GetJobStatus(void);

	//	To be used only by the Queue Manager
	int SetJobStatus(int iStatus);

/*
	//function called by the process to update progress
	//each time the function call is made, the number of units process is incremented by 1 (default setting).
	//if a process detects any exception, it can force its completion by setting iDone = true
	int UpdateProgress(int iCompleted = 1, bool iDone = false);

	//function called by the process to initialize progress reporting
	int InitializeProgressReporting(std::string iPathToJobFile, int iTotalN);

	//function called by the process to reset any previous progress information that was reported
	int ErasePreviousProgressInformation(std::string iPathToJobFile);
		
	//function called by the process to determine its progress 
	//returns number of units processed
	int GetProgress();

	//function called by the process to handover the path to a "list of units" it intends on (processig/analyzig/.../etc.)	
	int HandOverPathToUnitList(std::string iJobFile, std::string iPathToUnitList);

	//function called by the process to get the "list of units" from the QueueManager (for retry scenarios)
	//returns path to a file containing the "list of units"
	std::string GetPathToUnitList();
	
	//function called by the process to indicate to the QueueManager which "specific units" it processed.
	//the units reported are stored in a file and maintained by the QueueManager	
	int SetProcessedUnitNumber(int iUnitNum);

	//function called by the process to get a list of "specific units" it processed (for retry scenarios)
	//returns path to a file	
	std::string GetPathToSpecificUnitsProcessed();

	//function called by the process to determine if it is being retried
	int IsThisARetryAttempt(std::string iJobFile);

	//function to find out if a termination request has been generated by the user
//	int GetTerminationRequest();
*/
	ProgressAPI(int iJobID = 0)
	{		
		m_jobID = iJobID;
		m_total = 0;
		m_completed = 0;
		m_progressErased = 0;
		m_userID = 0;
//		m_db.InitDatabaseInfo();
	}

	~ProgressAPI()
	{
	}

private:

	//total number of units
	int m_total;

	//number of units processed
	int m_completed;

	//indicates whether previously reported progress was erased
	int m_progressErased;

	//process name is cached
	std::string m_processName;

	//job ID is cached
	std::string m_jobIDStr;

	//job file name is cached
	std::string m_filename;

	CPxDcmDB m_db;	
	int m_jobID;
	int m_userID;
};

/*
//----------------------------------------------------------
//
class JobInfoPublisherByDB : public JobInfoPublisherInterface
{
public:
	JobInfoPublisherByDB(int iJobID);
	virtual ~JobInfoPublisherByDB() {}

	virtual int SetInfo(KVP_MAP& iKVP);

	virtual int SetStatus(int iStatus);
	virtual void SetProgress(int iCompleted, int iTotal);

	virtual bool AmICancelled(void) { return false; }
	virtual void Clean(void) {}

protected:
	//	This will be called by the constructor
	virtual void Initialize(void);

	int m_status;
	int m_total;
	int m_completed;
	ProgressAPI m_progress;
};

//----------------------------------------------------------
//
class JobInfoSubscriberByDB: public JobInfoSubscriber
{
public:
	//	Use this to find jobIDs.  No need to use it if you already know the ids
	//		of the jobs of interest.
//	static int QueryJobs(KVP_MAP iConstraints, std::vector<int>& oJobIDs) {};

	JobInfoSubscriberByDB(int iJobID);
	virtual ~JobInfoSubscriberByDB() {}

	virtual int GetInfo(KVP_MAP& ioKVP) { return 0; }

	virtual int GetStatus(int& oStatus);
	virtual int GetProgress(int& oCompleted, int& oTotal);

	virtual int Cancel(void) { return 0; }

	virtual int Hide(void) { return 0; } 
protected:
	//	This will be called by the constructor
	virtual void Initialize(void) {}

	int m_jobID;
	ProgressAPI m_progress;
};
*/
#endif PROGRESS_API_H